sudo: required
language: python
python:
- '2.7'
env:
- HEROKU_STACK=heroku-18
services:
- docker
branches:
  only:
  - master
install: true
script: bash build.sh
deploy:
  provider: s3
  endpoint: https://sfo2.digitaloceanspaces.com
  skip_cleanup: true
  access_key_id: WMNE3YDAHTSHGVWXUHOZ
  secret_access_key:
    secure: AiCra48yidto4/jyrcEAZOoco+8oib4yB+YdrIqGXpGyuo7s8siQs3MUEKnuBC/vgF9a+WKtVPX3FJbAUxJ3wU35vmqwpi26DBxroMDKJjOVXl1EEEvN7Qmz6Tv1RfcEAn9J5W0aWZpRcrX0I6Cx++NOhG2TB/9/zFa4B39XlICyRJBk6grXYBgA3sug5wlgA/Ef5bdxT5yRBWqKLhHQGqy1ThFoa8Hw9cL3KMhHMzULiokpMr9evv4Ag7Hf6CX2VnhYFY+asDpNuJvN42vb307KMw6ZlhH8SRWv1TgyKZHezP8SxYcgCAGCtplODTLPA6R6iS7AbvFIvsR1VYet5nzWiGsyVfxGjJQDkJYaVA+rtyQDMgcxRt2dmed8pez5dhRgJAc4DSQ0p0Zzo48Qkz+KuhDQXy+tFukgKRGp3aKiRtkXR37WBy8KO4iEfgaEXjMhSBsvYrG9M8hcFlRRwD+NAEPcKAw6g5PAcFGKx6XNdMFPtLkvkTwqsIv0zI2suJRj6yOPG3/ppMdtI+vHtpYbA6JuS10yoxcx3X4VELlnE32zmtFkWS6HlHonLeggBUOhDVLiHnxyqGa0fIplFFLudYExkcHTfEBwA0GnxO4crnkTfqTaffrXr1R8dagb0Dfx9Pl9khr0JbPcLOpYZUEv9rNUxshXvipsD3JdnNo=
  bucket: heroku-buildpack-elixir
  local-dir: "$TRAVIS_BUILD_DIR/builds/otp"
  upload-dir: erlang
  acl: public_read
  on:
    repo: chefconnie/heroku-buildpack-elixir-otp-builds
